code/modules/client/preferences.dm
code/modules/client/preferences/_preference.dm
code/modules/mob/living/carbon/human/human_helpers.dm
code/modules/unit_tests/preferences.dm
modular_novus/code/datums/headshot.dm
modular_novus/code/modules/client/preferences/flavor.dm
modular_novus/code/modules/jobs/job_types/_job.dm
modular_novus/code/modules/mob/living/living_defines.dm
modular_novus/code/modules/mob/living/living_verbs.dm
tgstation.dme
tgui/packages/tgui/interfaces/HeadshotPanel.js
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/headshot.tsx

Headshots + Examine panel as a whole + Flavor Text(s)
One step closer to Skyrat or something
:cl:
add: adds headshots and examine panel
add: adds flavor texts
/:cl:

FT/Examine Panel (hopefully unbuggy)

---

code/modules/mob/living/carbon/carbon_verbs.dm

Fixes compilation

---

code/modules/mob/living/carbon/human/_species.dm

Fixes that one bug probably.

---

code/modules/clothing/gloves/insulated.dm

Title
LET ME USE MY BATONS THANK YOU
:cl:
balance: insulated gloves no longer prevent you from using guns
/:cl:

Insuls no longer give you chunky fingers

---

code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
code/modules/reagents/withdrawal/generic_addictions.dm

title
i need my ass buffs
:cl:
balance: hooch heals assistants again
/:cl:

Hooch heals assistants again

---

code/game/objects/items/food/cake.dm
code/modules/mob/living/carbon/human/species_types/felinid.dm
code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm
code/modules/surgery/organs/internal/liver/liver_felinid.dm
tgstation.dme

Title.
We need more ways to kill them.
:cl:
qol: felinids can again be killed with chocolate-based products
/:cl:

Felinids now take organ damage from cocoa

---

code/__DEFINES/organs.dm
code/datums/sprite_accessories/genitals.dm
code/modules/mob/living/carbon/human/_species.dm
code/modules/surgery/bodyparts/bodypart_overlays/mutant_bodypart_overlay.dm
code/modules/surgery/organs/external/genitals.dm

Thanks linnepap for bringing awareness to this
fixes genital skintone handling and sprite accessory getting set to blank which is NOT awesome!
the ocky way
nah

Goon sesh fixes but like, the ocky way

---

code/_globalvars/admin.dm
code/modules/admin/sql_ban_system.dm
code/modules/client/client_procs.dm
code/modules/client/preferences/broadcast_login_logout.dm
code/modules/client/preferences/ooc.dm

yeah so you know that baby weak text observers get when someone rejoins
yeah it's AWESOME now
lowpop problems require lowpop solutions that will be dumped later anyways
:cl:
add: client login/logout now displays to all players
del: removed login/out broadcast preference
/:cl:

Login/Logout text except AWESOME

---

code/__HELPERS/sanitize_values.dm
code/datums/sprite_accessories.dm
code/modules/client/preferences.dm
code/modules/client/preferences/_preference.dm
code/modules/client/preferences/mutant.dm
code/modules/client/preferences/species_features/felinid.dm
code/modules/client/preferences/species_features/genitals/breasts.dm
code/modules/client/preferences/species_features/genitals/penis.dm
code/modules/client/preferences/species_features/genitals/testicles.dm
code/modules/client/preferences/species_features/genitals/vagina.dm
code/modules/client/preferences/species_features/lizard.dm
code/modules/client/preferences/species_features/mutants.dm
code/modules/mob/living/carbon/human/_species.dm
code/modules/surgery/bodyparts/bodypart_overlays/mutant_bodypart_overlay.dm
code/modules/surgery/organs/organ_restyling.dm
code/modules/surgery/organs/organ_visual.dm
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx

I haven't even begun actually porting sprite accessories, or doing any significant frontend work...
Yet I'm already going actually insane.
i stole most of this from https://github.com/Artea-Station/Artea-Station-Server/pull/139 thanks Rimi
m

Colorjakking episode III: Revenge of the shit

---

code/_globalvars/admin.dm
code/modules/admin/sql_ban_system.dm
code/modules/client/client_procs.dm
code/modules/client/preferences/broadcast_login_logout.dm
code/modules/client/preferences/ooc.dm

YOU FUCKED UP SMALL TIME, NULL

Revert "Login/Logout text except AWESOME"

---

code/_globalvars/lists/flavor_misc.dm
code/datums/sprite_accessories.dm
code/modules/client/preferences.dm
code/modules/client/preferences/species_features/felinid.dm
code/modules/client/preferences/species_features/genitals/breasts.dm
code/modules/client/preferences/species_features/genitals/penis.dm
code/modules/client/preferences/species_features/genitals/testicles.dm
code/modules/client/preferences/species_features/genitals/vagina.dm
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/genitals.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx

Colorjakking IV: This was supposed to be part of Colorjakking III but i fat fingered the merge button before pushing the last commit

---

code/game/objects/items/rcd/RPLD.dm
code/modules/liquids/liquid_atoms/turfs.dm
code/modules/surgery/organs/external/genitals.dm
code/modules/unit_tests/create_and_destroy.dm

Fixes unit tests maybe

---

code/_globalvars/admin.dm
code/modules/admin/sql_ban_system.dm
code/modules/client/client_procs.dm
code/modules/client/preferences/broadcast_login_logout.dm
code/modules/client/preferences/ooc.dm
tgstation.dme

Revert "Revert "Login/Logout text except AWESOME""

---

code/game/machinery/computer/robot.dm
code/modules/mob/living/silicon/robot/robot_defines.dm
tgui/packages/tgui/interfaces/RoboticsControlConsole.js

it works yes
:cl:
balance: borgs can be blown up again
/:cl:

You can now blow up borgs again

---

code/datums/diseases/gastrolisis.dm
code/modules/client/preferences/flavor.dm
code/modules/surgery/organs/internal/tongue/_tongue.dm

Finishes up the work of Linnepap for custom say verbs
Slightly better and more expandable code i guess
no

Tongue up my asshole

---

code/datums/diseases/gastrolisis.dm
code/modules/surgery/organs/internal/tongue/_tongue.dm

That snowflake proc sucks
I just replaced it with before_organ_replacement() thus simplifying code
fuck you
no

Tongue up my asshole 2

---

code/__DEFINES/chat.dm
code/__DEFINES/span.dm
code/modules/balloon_alert/balloon_alert.dm
code/modules/client/preferences.dm
code/modules/liquids/liquid.dm
tgui/packages/tgui-panel/chat/constants.js
tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
tgui/packages/tgui-panel/styles/tgchat/chat-light.scss

Balloon alerts also create chat messages now
https://github.com/NovusSS13/NovusSS13/assets/82850673/e2ba26b4-5508-4620-9885-09e36b60ce9d
Balloon alerts are the worst fucking zoomer fortnite feature TG has added in ages. They significantly reduce the usefulness of chat by reducing logging ability, on top of just looking fucking vile.
This will fix the first half. It still looks ugly. The chat message also looks fugly.
To be fixed. Fuck you. Fucking fortnite zoomer ADHD shit. God fucking damn it.
:cl:
add: Balloon alert chat text
/:cl:

fuck balloon alerts dude

---

code/controllers/configuration/entries/agegate.dm
code/controllers/configuration/entries/general.dm
code/game/world.dm
config/config.txt
tgstation.dme

Adds a bunch of cool things to the hub entry.
Because we have to stand out

Server tagline and other hub entry changes

---

code/game/world.dm

I AM . A MORON! WHO DOES NOT TEST HIS CODE!!!!

Config fix

---

code/modules/client/preferences/middleware/markings.dm
tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/MarkingsPage.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/data.ts

uhhhhhh You Can See The Markings

better marking selection menu

---

code/modules/client/preferences/middleware/markings.dm

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

makes marking spritesheet cross round cachable

---

config/rules.json

It's still "we the people", right?

Rules grammar and extra clarification

---

config/rules.json

Byeah
Matches our discord, and I think it looks better like this

Reorders rules so principles come first

---

config/rules.json

Fixes incorrect (british) spelling on the rules (behaviour instead of behavior)
Toxic Garbage Island

Dude i hate brits lol

---

code/game/world.dm

Brought to you by

---

code/__DEFINES/mobs.dm
code/datums/components/crafting/misc.dm
code/datums/examine_panel.dm
code/game/area/areas/shuttles.dm
code/game/machinery/computer/orders/order_items/mining/order_mining.dm
code/modules/antagonists/ashwalker/ashwalker.dm
code/modules/client/preferences/flavor.dm
code/modules/mining/lavaland/necropolis_chests.dm
html/changelogs/AutoChangeLog-pr-17.yml
tgui/packages/tgui/interfaces/ExaminePanel.js

Unfucks custom speech verbs

---

code/datums/sprite_accessories/tails.dm
code/modules/mob/living/carbon/human/_species.dm
code/modules/surgery/bodyparts/bodypart_overlays/mutant_bodypart_overlay.dm
code/modules/surgery/organs/external/tails.dm

this monkey shit is driving me insane

(Attempts to) Fix the screenshot unit tests once and for all

---

config/rules.json

Adds an antagonist principles section to make it clear what we want out of antagonists on the server.

Small rules update - Antagonists

---

code/modules/surgery/bodyparts/bodypart_overlays/helpers.dm

Unfucks arm markings

---

code/datums/emotes.dm

chat color ghost fix

---

code/modules/client/preferences.dm
code/modules/client/preferences/body_size.dm
code/modules/client/preferences/body_type.dm
code/modules/client/preferences/height.dm
code/modules/client/preferences/runechat.dm
tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
tgui/packages/tgui/interfaces/PreferencesMenu/MarkingsPage.tsx

small character setup improvers

---

code/modules/mob/living/carbon/human/human_defines.dm

pref to set your own char to bilinear coming soon i dont care right now
humans are nearest neighbor again

PIXEL_SCALE

---

code/__DEFINES/chat.dm
code/__DEFINES/preferences.dm
code/__DEFINES/speech_channels.dm
code/__HELPERS/text.dm
code/datums/keybinding/communication.dm
code/game/objects/structures/mannequin.dm
code/modules/client/preferences/middleware/random.dm
code/modules/client/preferences/runechat.dm
code/modules/mob/dead/new_player/preferences_setup.dm
code/modules/tgui_input/say_modal/modal.dm
code/modules/tgui_input/say_modal/speech.dm
tgui/packages/tgui-panel/chat/constants.js
tgui/packages/tgui-say/ChannelIterator.ts
tgui/packages/tgui-say/styles/colors.scss
tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx

Adds looc for tgui say
adds looc keybinding
fixes close button on character setup
das ist good
:cl:
qol: LOOC keybind and LOOC tgui say
fix: Fixed character setup close buttons working improperly
/:cl

Hotfixes for playtest

---

code/datums/keybinding/living.dm
code/modules/mob/dead/new_player/preferences_setup.dm

RANDOMIZE_BY_DEFAUT

---

code/__HELPERS/mobs.dm
code/modules/antagonists/heretic/magic/flesh_surgery.dm
code/modules/mob/mob_helpers.dm
code/modules/surgery/bodyparts/head_hair_and_lips.dm
code/modules/surgery/bodyparts/parts.dm
code/modules/surgery/organs/helpers.dm

Title
These refuse to change direction because i added them as overlays on top of overlays
Things working as intended is good
meh nah

Gets rid of butchered usage of emissives and emissive blockers in surgery code

---

code/modules/surgery/bodyparts/bodypart_overlays/mutant_bodypart_overlay.dm

fixes mutant organ coloring

---

code/datums/status_effects/debuffs/disgust.dm

BAHHHHHHHHHHHHa

---

code/modules/mob/living/emote.dm

Deathgasp should not vary

---

config/splashtext.txt

Splash text upgate

---

code/_onclick/click.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/mob.dm
code/modules/point/point.dm

Ports https://github.com/Sandstorm-Station/Sandstorm-Station-13/pull/324 with no rotating because it looks awful when rotated
Soul
:cl:
add: Pixel pointing
/:cl:

Pixel pointing the ocky way

---

code/game/say.dm
code/modules/mob/living/carbon/human/examine.dm

Don't slam the merge button careless

---

code/modules/liquids/liquid.dm

This looks bad
The examine chain needs a bit of reworking, this will do for now
nah

Removes <hr> on liquid puddles

---

code/game/objects/items/storage/wallets.dm
code/modules/modular_computers/computers/item/computer.dm

It wasn't using cached_flat_icon
ugly = bad

Fixes id icons on examine not displaying properly

---

code/modules/client/preferences/middleware/species.dm

Species preview icons shouldn't be naked on character setup

---

code/game/objects/items/cards_ids.dm

fixes ids showing a photo of a photo

---

code/modules/client/verbs/ooc.dm
tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
tgui/packages/tgui-panel/styles/tgchat/chat-light.scss

Fixes LOOC

---

code/controllers/subsystem/statpanel.dm
code/datums/brain_damage/mild.dm
code/datums/interactions/_interaction.dm
code/game/objects/items/cards_ids.dm
code/modules/mob/dead/dead.dm
code/modules/mob/living/brain/brain_say.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human_say.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_say.dm
code/modules/unit_tests/say.dm
html/statbrowser.js
tgui/packages/tgui/interfaces/IdCardPanel.tsx

Miscellaneous small changes
I'm a stud, I'm ballsy, I don't have to explain my changes... Unlike you!
:cl:
add: The dumb brain trauma makes you drool.
add: You can now see the player count in the status tab
qol: Say sentences automatically get punctuation at the end now
/:cl:

Shenanigans

---

code/game/objects/items/storage/wallets.dm
code/modules/modular_computers/computers/item/computer.dm

Always use get_examine_string() on get_id_examine_strings()

---

code/game/say.dm
code/modules/mob/living/carbon/carbon_say.dm

fixes say colors

---

code/modules/mob/living/blood.dm
code/modules/mob/living/carbon/human/examine.dm

blood fixes n shiet

---

code/datums/interactions/saygex/masturbation.dm
code/game/world.dm
code/modules/mob/living/carbon/carbon_saygex.dm
code/modules/mob/living/carbon/carbon_update_icons.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/reagents/chemistry/reagents.dm
code/modules/surgery/organs/external/genitals.dm

fixes a bunch of issues i noticed or that were reported by players

---

code/datums/components/bloodysoles.dm

Fixes the bloodysoles infinite recursion loop

---

code/__DEFINES/role_preferences.dm
code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
code/modules/antagonists/brother/brother.dm
code/modules/mob/living/carbon/alien/alien_update_icons.dm
config/dynamic.json

Beats up the default dynamic config into a bloody pullp
Default TG configs are wack, they have very low threat costs especially. Let's fuck with config until it works out.
:cl:
add: Blood brothers now can be a midround antag
/:cl:

Makes dynamic not awful

---

code/game/gamemodes/dynamic/dynamic_rulesets.dm
config/dynamic.json
tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/bloodbrother.ts
tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/bloodbrothermidround.ts

fixes some oopsies with dynamic config

---

code/modules/surgery/bodyparts/_bodyparts.dm

Title
Fixes it in the simplest way really
I should eventually convert all uses of images in bodyparts to mutable_appearance now that this is done but meh
:cl:
fix: Fixed visual oddities with bodyparts
/:cl:

Fixes dropped bodyparts having their overlays change dirs

---

code/datums/interactions/saygex/masturbation.dm
code/modules/liquids/liquid.dm

fixes a runtime and doubled examine message on liquids

small fixes

---

code/__DEFINES/role_preferences.dm
code/datums/status_effects/debuffs/disgust.dm

aids, blood brother midround antag icon fix

stomach aid funny disgust refactor bug

---

code/datums/brain_damage/severe.dm
code/datums/emotes.dm
code/game/say.dm
code/modules/mob/living/carbon/carbon_update_icons.dm
code/modules/mob/living/living_say.dm
code/modules/mob/mob.dm

more dumb fixes

---

code/game/objects/effects/decals/cleanable/blood/particle.dm
code/modules/mob/living/carbon/human/_species.dm

possibly fixes voice pack issues

---

code/_globalvars/lists/mobs.dm
code/game/machinery/computer/records/medical.dm
code/modules/client/preferences/blood_type.dm
tgstation.dme
tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/blood_type.tsx

Title
Minor balance implications for the sake of character customization
:cl:
add: Blood type preference
/:cl:

Blood type preference

---

code/modules/client/preferences/middleware/markings.dm

515 compatibility chungus
PROC_REF() is there for a reason
no

replaces bad .proc/ usage with PROC_REF()
